// AUTOGENERATED BY scripts/build-index.js
// DO NOT MODIFY

export * from "./clusterrole";
export * from "./clusterrolebinding";
export * from "./policyrule";
export * from "./role";
export * from "./rolebinding";
export * from "./roleref";
export * from "./subject";
