export enum KeyUsage {
    Signing = "signing",
    DigitalSignature = "digital signature",
    ContentCommitment = "content commitment",
    KeyEncipherment = "key encipherment",
    KeyAgreement = "key agreement",
    DataEncipherment = "data encipherment",
    CertSign = "cert sign",
    CRLSign = "crl sign",
    EncipherOnly = "encipher only",
    DecipherOnly = "decipher only",
    Any = "any",
    ServerAuth = "server auth",
    ClientAuth = "client auth",
    CodeSigning = "code signing",
    EmailProtection = "email protection",
    SMIME = "s/mime",
    IPsecEndSystem = "ipsec end system",
    IPsecTunnel = "ipsec tunnel",
    IPsecUser = "ipsec user",
    Timestamping = "timestamping",
    OCSPSigning = "ocsp signing",
    MicrosoftSGC = "microsoft sgc",
    NetscapeSGC = "netscape sgc",
}
