#!/usr/bin/node

const fs = require("fs");

const basepath = __dirname + "/../src/types/";
const apiGroups = fs.readdirSync(basepath).filter(d => fs.lstatSync(basepath + d).isDirectory());
console.log(apiGroups);

for (const apiGroup of apiGroups) {
    const apiGroupPath = `${__dirname}/../src/types/${apiGroup}/`;
    const apiGroupVersions = fs.readdirSync(apiGroupPath);
    console.log(apiGroupVersions);

    for (const version of apiGroupVersions) {
        const versionPath = `${apiGroupPath}/${version}/`;
        const files = fs.readdirSync(versionPath).filter(f => f !== "index.ts" && f.endsWith(".ts"));
        //console.log(files)

        let str = `// AUTOGENERATED BY scripts/build-index.js\n// DO NOT MODIFY\n\n`;
        for (let file of files) {
            file = file.replace(".ts", "");
            str += `export * from "./${file}";\n`;
        }

        fs.writeFileSync(versionPath + "/index.ts", str);
    }
}