export enum StatusReason {
    Unknown = "",
    Unauthorized = "Unauthorized",
    Forbidden = "Forbidden",
    NotFound = "NotFound",
    AlreadyExists = "AlreadyExists",
    Conflict = "Conflict",
    Invalid = "Invalid",
    ServerTimeout = "ServerTimeout",
    Timeout = "Timeout",
    TooManyRequests = "TooManyRequests",
    BadRequest = "BadRequest",
    MethodNotAllowed = "MethodNotAllowed",
    NotAcceptable = "NotAcceptable",
    RequestEntityTooLarge = "RequestEntityTooLarge",
    UnsupportedMediaType = "UnsupportedMediaType",
    InternalError = "InternalError",
    Expired = "Expired",
    ServiceUnavailable = "ServiceUnavailable",
}
