name: Publish to NPM
on:
  push:
    tags: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "18.x"
      - run: npm config set '//registry.npmjs.org/:_authToken' "${{ secrets.NPM_TOKEN }}"
      - run: yarn
      - run: yarn compile
      - run: git config --global user.email opensource@mittwald.de
      - run: git config --global --replace-all user.name "Mittwald Release Bot"
      - run: npm version --no-git-tag-version from-git
      - run: cp README.md package.json dist/
      - run: cd dist && npm publish
